#!/bin/bash	
	
VERSION="$1"	
KUBECTL_PATH=/usr/local/kubectl/versions	
	
if [ -z "$VERSION" ]; then	
  echo "No version specified!"	
  exit 1	
else	
  VERSION="v$VERSION"	
fi	
# If the requested version is not a symlink or the version reqeusted, install and update the link	
if [ ! -f "$KUBECTL_PATH/$VERSION/kubectl" ] || [ ! "$(readlink /usr/local/bin/kubectl)" = "$KUBECTL_PATH/$VERSION/kubectl" ]; then	
  # If the version isn't installed, install it	
  if [ ! -f $KUBECTL_PATH/$VERSION/kubectl ]; then	
    # Determine which system we're on	
    case "$(uname -s)" in	
      Linux*)  SYSTEM=linux;;	
      Darwin*) SYSTEM=darwin;;	
      *)       echo "Unknown system!"; exit 1	
    esac	
	
    mkdir -p /usr/local/kubectl/versions/$VERSION	
    curl -L "https://storage.googleapis.com/kubernetes-release/release/$VERSION/bin/$SYSTEM/amd64/kubectl" -o $KUBECTL_PATH/$VERSION/kubectl	
    chmod +x $KUBECTL_PATH/$VERSION/kubectl	
  fi	
	
  # Update the symlink	
  ln -sf $KUBECTL_PATH/$VERSION/kubectl /usr/local/bin/kubectl	
fi
